# Generated by Django 2.2.3 on 2020-04-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('telefono', models.IntegerField(null=True)),
                ('dni', models.CharField(max_length=40, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('apellido', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('numeroserie', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('fechaa', models.DateField()),
                ('fechapm', models.DateField()),
                ('proveedor', models.CharField(max_length=200)),
                ('planta', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroref', models.CharField(max_length=50, null=True)),
                ('titulo', models.CharField(max_length=50, null=True)),
                ('descripcion', models.CharField(max_length=50, null=True)),
                ('fechaa', models.DateField(null=True)),
                ('fechapm', models.DateField(null=True)),
                ('urgencia', models.CharField(max_length=50, null=True)),
                ('tipo', models.CharField(max_length=50, null=True)),
                ('estado', models.CharField(max_length=50, null=True)),
                ('empleado', models.CharField(default=0, max_length=50)),
                ('comentarios', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
