# Generated by Django 3.0.5 on 2020-04-20 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_colaborativo', '0002_auto_20200416_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='fechaa',
            new_name='fecha_adquisicion',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='fechapm',
            new_name='fecha_puesta_marcha',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='fechaa',
            new_name='fecha_apertura',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='fechapm',
            new_name='fecha_resolucion',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='ticket',
        ),
    ]
