# Generated by Django 3.0.5 on 2020-04-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_colaborativo', '0004_auto_20200423_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='proveedor',
            field=models.CharField(max_length=100),
        ),
    ]
