# Generated by Django 3.0.5 on 2020-04-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_colaborativo', '0005_auto_20200423_1214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
