# Generated by Django 2.2.3 on 2020-05-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_colaborativo', '0006_delete_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='descripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('abierto', 'ABIERTO'), ('cerrado', 'CERRADO')], default='abierto', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tipo',
            field=models.CharField(choices=[('avería', 'AVERÍA'), ('mejora', 'MEJORA'), ('mantenimiento', 'MANTENIMIENTO')], default='avería', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='urgencia',
            field=models.CharField(choices=[('urgente', 'URGENTE'), ('alta', 'ALTA'), ('media', 'MEDIA'), ('baja', 'BAJA')], default='urgente', max_length=50, null=True),
        ),
    ]
