# Generated by Django 2.2.3 on 2020-05-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_colaborativo', '0007_auto_20200527_1710'),
    ]

    operations = [
        migrations.DeleteModel(
            name='descripcion',
        ),
    ]
